### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by iamdriz** [weixiyen/messenger.js#13]
If I have sever listening on one process and then kill the process that has the client requesting I get the error ECONNRESET... Any ideas on how to stop this?

The full erorr is:

```
Uncaught exception:
Error: read ECONNRESET
  at exports.errnoException (util.js:846:11)
  at TCP.onread (net.js:540:26)
```

**Comment by MoLow** [comment]
https://github.com/weixiyen/messenger.js/pull/15
