### ISSUE TITLE
Crash on 'npm start'

### ISSUE THREAD

**Issue by dukeimg** [weixiyen/messenger.js#16]
Cannot start npm server on Windows 10. Log says that there is a problem with messenger
- node v5.9.1
- npm  v3.7.3

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.7.3
3 info using node@v5.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle messenger@1.0.0~prestart: messenger@1.0.0
6 silly lifecycle messenger@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle messenger@1.0.0~start: messenger@1.0.0
8 verbose lifecycle messenger@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle messenger@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\dukei\Documents\Projects\messenger_angular2\node_modules\.bin;C:\Program Files\nodejs;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\PostgreSQL\9.5\bin;C:\RailsInstaller\Ruby2.2.0\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\RailsInstaller\Ruby2.2.0\bin;C:\Users\dukei\AppData\Roaming\npm
10 verbose lifecycle messenger@1.0.0~start: CWD: C:\Users\dukei\Documents\Projects\messenger_angular2
11 silly lifecycle messenger@1.0.0~start: Args: [ '/d /s /c', 'concurrently "npm run tsc:w" "npm run lite" ' ]
12 silly lifecycle messenger@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle messenger@1.0.0~start: Failed to exec start script
14 verbose stack Error: messenger@1.0.0 start: `concurrently "npm run tsc:w" "npm run lite" `
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid messenger@1.0.0
16 verbose cwd C:\Users\dukei\Documents\Projects\messenger_angular2
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.9.1
20 error npm  v3.7.3
21 error code ELIFECYCLE
22 error messenger@1.0.0 start: `concurrently "npm run tsc:w" "npm run lite" `
22 error Exit status 1
23 error Failed at the messenger@1.0.0 start script 'concurrently "npm run tsc:w" "npm run lite" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the messenger package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     concurrently "npm run tsc:w" "npm run lite"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs messenger
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls messenger
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by dukeimg** [comment]
I tried to run a project, cloned from github. The problem was in the `node_modules` folder. I just deleted it and run `npm install`. All works after.
